version: '3.8'

services:
  backend:
    build: .
    container_name: news-portal-backend
    env_file:
    - .env  
    depends_on:
      - db
      - redis
      - kafka
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/newsdb
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:9092
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: news-portal-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: news-portal-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: news-portal-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: news-portal-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

volumes:
  postgres_data: