name: FastAPI CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
      # postgres:
      #   image: postgres:15
      #   env:
      #     POSTGRES_USER: user
      #     POSTGRES_PASSWORD: password
      #     POSTGRES_DB: newsdb
      #   ports:
      #     - 5432:5432
      #   options: >-
      #     --health-cmd "pg_isready -U user -d newsdb"
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5

      # redis:
      #   image: redis:latest
      #   ports:
      #     - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting (black & isort)
        run: |
          pip install black isort
          black --check .
          isort --check-only .

      # - name: Run tests
      #   env:
      #     POSTGRES_USER: user
      #     POSTGRES_PASSWORD: password
      #     POSTGRES_DB: newsdb
      #     REDIS_HOST: localhost
      #     REDIS_PORT: 6379
      #   run: |
      #     pip install pytest
      #     pytest -v
